name: SLSA Provenance with Custom Signing

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  generate-and-sign-provenance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Install SLSA generator
      run: |
        go install github.com/slsa-framework/slsa-github-generator/actions/run@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Run SLSA generator
      id: provenance
      run: |
        mkdir -p output
        run --output-path output/ --upload=false
        echo "Generated provenance: $(ls output/)"

    - name: Extract provenance file
      run: |
        cp output/*.intoto.jsonl provenance.intoto.jsonl

    - name: Decode .intoto.jsonl to provenance.json (optional)
      run: |
        jq -s '.[0]' provenance.intoto.jsonl > provenance.json

    - name: Setup Cosign key
      run: |
        echo "${{ secrets.COSIGN_KEY }}" > cosign.key
        chmod 600 cosign.key

    - name: Sign provenance with key
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        cosign sign-blob --key cosign.key --output-signature provenance.sig provenance.json

    - name: Show signature
      run: cat provenance.sig
