name: SLSA Provenance with Custom Signing

on:
  push:
    branches: [main]

permissions:
  id-token: write  # Required for SLSA keyless
  contents: read

jobs:
  generate-and-sign-provenance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 1: Generate provenance using SLSA generic-generator
    - name: Generate SLSA Provenance
      uses: slsa-framework/slsa-github-generator/generic-generator@v1.10.0
      with:
        command: echo "Hello world"
        output-artifact-name: hello.txt

    - name: List provenance files
      run: ls -l ./artifact

    # Step 2: Decode DSSE provenance to JSON (optional)
    - name: Extract inner payload
      run: |
        jq -r '.payload' artifact/*.intoto.jsonl | base64 -d > provenance.json

    # Step 3: Set up Cosign
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    # Step 4: Restore Cosign private key
    - name: Prepare cosign.key
      run: |
        echo "${{ secrets.COSIGN_KEY }}" > cosign.key
        chmod 600 cosign.key

    # Step 5: Sign the provenance.json file
    - name: Sign provenance.json
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        cosign sign-blob --key cosign.key --output-signature provenance.sig provenance.json

    - name: Show signature
      run: cat provenance.sig


